version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_virustotal
    ports:
      - "8000:8000"
    environment:
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - API_URL=${API_URL}
    volumes:
      - .:/app
    restart: always
